### ISSUE TITLE
 system分区无法写入

### ISSUE THREAD

**Issue by Hunerk** [Lerist/fakelocation.github.io#4]
S10  Android 9.0+已ROOT， 刷了第三方包。但还是不能写system. 根据你的说明，使用Syslock 解锁分区失败。粘贴进 Magisk Manager 设置里的自定义更新通道里,打开Magisk后一直是正在检查更新。就没反应了，接下来怎么弄。有没有QQ群之类的好交流。

**Comment by Lerist** [comment]
V1.2.0.2 已不需要解锁system分区
