### ISSUE TITLE
我只是用来钉钉打开,是否需要root权限呢

### ISSUE THREAD

**Issue by shizeying** [Lerist/fakelocation.github.io#8]

**Comment by Lerist** [comment]
可以不需要ROOT权限, 避免检测请参考 [常见问题](https://github.com/Lerist/fakelocation.github.io/blob/master/FAQ/zh/FAQ.md#10%E9%81%BF%E5%85%8D%E8%A2%ABdd%E6%A3%80%E6%B5%8B2019%E5%B9%B47%E6%9C%889%E6%97%A5-%E6%9B%B4%E6%96%B0)第十条里NOROOT模式的方法
